// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQZNHAHMnmaernfGttY28HQNIE0BWsowI',
    appId: '1:960189514323:web:0d44a67d90366c0a9d7ca6',
    messagingSenderId: '960189514323',
    projectId: 'healingbee-firebase',
    authDomain: 'healingbee-firebase.firebaseapp.com',
    databaseURL: 'https://healingbee-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'healingbee-firebase.appspot.com',
    measurementId: 'G-FCG5ECC2CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKP1hGxbHVILn6RegnBZnOMVv0aL24X8o',
    appId: '1:960189514323:android:3dd79a03ad9333359d7ca6',
    messagingSenderId: '960189514323',
    projectId: 'healingbee-firebase',
    databaseURL: 'https://healingbee-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'healingbee-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXU-kduxv8seBmLu_NUtDGEUFEDN1KQDQ',
    appId: '1:960189514323:ios:825ee1bb4749a09d9d7ca6',
    messagingSenderId: '960189514323',
    projectId: 'healingbee-firebase',
    databaseURL: 'https://healingbee-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'healingbee-firebase.appspot.com',
    androidClientId: '960189514323-it9hm5h0pv7rlp0eu5fbo14735ilfs24.apps.googleusercontent.com',
    iosClientId: '960189514323-481oonhldaemq4udlusktaha125o3p6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXU-kduxv8seBmLu_NUtDGEUFEDN1KQDQ',
    appId: '1:960189514323:ios:825ee1bb4749a09d9d7ca6',
    messagingSenderId: '960189514323',
    projectId: 'healingbee-firebase',
    databaseURL: 'https://healingbee-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'healingbee-firebase.appspot.com',
    androidClientId: '960189514323-it9hm5h0pv7rlp0eu5fbo14735ilfs24.apps.googleusercontent.com',
    iosClientId: '960189514323-481oonhldaemq4udlusktaha125o3p6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQZNHAHMnmaernfGttY28HQNIE0BWsowI',
    appId: '1:960189514323:web:ca8886aecdce193e9d7ca6',
    messagingSenderId: '960189514323',
    projectId: 'healingbee-firebase',
    authDomain: 'healingbee-firebase.firebaseapp.com',
    databaseURL: 'https://healingbee-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'healingbee-firebase.appspot.com',
    measurementId: 'G-Q17QZR1N34',
  );
}
